export const ADD_MOVIE = 'ADD_MOVIE'
export const RESET_MOVIES = 'RESET_MOVIES'
export const FETCH_MOVIES_PENDING = 'FETCH_MOVIES_PENDING';
export const FETCH_MOVIES_COMPLET = 'FETCH_MOVIES_COMPLET';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';
export const ADD_MOVIE_ERROR = 'ADD_MOVIE_ERROR';
export const RESET_ERROR_STATE = 'RESET_ERROR_STATE'
export const ADD_MOVIE_PENDING = 'ADD_MOVIE_PENDING'