export const ADD_MOVIE = 'ADD_MOVIE'
export const RESET_MOVIES = 'RESET_MOVIES'
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_COMPLET = 'FETCH_MOVIES_COMPLET';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';
